### ISSUE TITLE
Chicago95 title

### ISSUE THREAD

**Issue by Santarina** [dominichayesferen/Chicagofier#2]
How to change Chicago95 title in start menu to Windows 95?

**Comment by dominichayesferen** [comment]
That's a question for https://github.com/grassmunk/Chicago95/issues .

**Comment by Santarina** [comment]
I found it. Just go to ~/.themes/Chicago95/gtk-3.24/apps/whiskermenu.css. Open it and search for branding_C95_aliased.png and rename to branding_W95-orig.png. Save it and restart linux
