### ISSUE TITLE
Icons have forced green background

### ISSUE THREAD

**Issue by Bandav-Lohengrin** [dominichayesferen/Chicagofier#6]
Ubuntu 20.04
Linux Mint 20.03
Idk if this is intentional or not, but no matter what config you have, the titles of the icons have the same green background. Makes changing the wallpaper kind of a bummer ngl. (Also I saw in the yt video that once the installer is installed, the wallpaper automatically changes to the green stock one, but this didn't happen to me either, but since the wallpaper is easily changed, I don't mind this)
![image](https://github.com/dominichayesferen/Chicagofier/assets/142371786/59e6ea26-dfc4-4722-a769-df0f84c22fcd)

**Comment by dominichayesferen** [comment]
I'm pretty sure that's just a deliberate choice by upstream Chicago95, given the source material always did the same itself.

Closing this issue since, yeah, I know for a fact this is something controlled by the GTK theme (and therefore is Chicago95's 'issue' not this's).
