### ISSUE TITLE
How do I uninstall it?

### ISSUE THREAD

**Issue by H4ppyC4t** [dominichayesferen/Chicagofier#7]
My dumb ass didn't read that this was only for xubuntu and decided to run it on EndeavourOS and as expected, it didn't work that well. I have no idea to uninstall it so I need some help. Thanks and have a good day

**Comment by dominichayesferen** [comment]
At the beginning of the script's superuser and userland modes is a command each to uninstall the script's added files and folders - run both of those commands to uninstall it.

Then, uninstalling the rest is done through the Chicago95 installer itself, if implemented.
